<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit125dddd280a32cf75b181166154246ec
{
    public static $files = array (
        '2cffec82183ee1cea088009cef9a6fc3' => __DIR__ . '/..' . '/ezyang/htmlpurifier/library/HTMLPurifier.composer.php',
    );

    public static $prefixesPsr0 = array (
        'P' => 
        array (
            'PronounceableWord_' => 
            array (
                0 => __DIR__ . '/..' . '/gnugat/PronounceableWord/src',
            ),
            'PhpImap' => 
            array (
                0 => __DIR__ . '/..' . '/php-imap/php-imap/src',
            ),
        ),
        'H' => 
        array (
            'HTMLPurifier' => 
            array (
                0 => __DIR__ . '/..' . '/ezyang/htmlpurifier/library',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInit125dddd280a32cf75b181166154246ec::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
