<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'PronounceableWord_' => array($vendorDir . '/gnugat/PronounceableWord/src'),
    'PhpImap' => array($vendorDir . '/php-imap/php-imap/src'),
    'HTMLPurifier' => array($vendorDir . '/ezyang/htmlpurifier/library'),
);
